const STORAGE_KEY='nainaMoneyDataV1';
const CREDENTIAL={user:'Naina03',hash:'dc0ae8fa481e47bb6427733aa210979aca5b715f07ad458b4879a0fa84dbeecc'};
const money=n=>`৳${new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n||0)}`;
const seed={
  originalLandSale:3375000,
  transactions:[
    {id:1,date:'2025-01-01',type:'Opening Balance',details:'First land sale instalment',amountIn:2500000,amountOut:0,notes:'৳25 lakh received'},
    {id:2,date:'2025-08-10',type:'Loan Given',details:'Riaz Loan',amountIn:0,amountOut:100000,notes:'Refundable',person:'Riaz'},
    {id:3,date:'2025-09-10',type:'Saving/FDR',details:'Naina BRAC FDR',amountIn:0,amountOut:1000000,notes:'3 months, Acc: 1066151570001'},
    {id:4,date:'2025-12-10',type:'Saving/FDR',details:'Naina BRAC FDR',amountIn:0,amountOut:1000000,notes:'3 months, Acc: 1066151570001'},
    {id:5,date:'2026-01-05',type:'Spend',details:'Khoka bKash',amountIn:0,amountOut:20000,notes:''},
    {id:6,date:'2026-01-06',type:'Spend',details:'Naina Mother bKash',amountIn:0,amountOut:5000,notes:''},
    {id:7,date:'2026-01-07',type:'Spend',details:'Phone for Naina Mother',amountIn:0,amountOut:30000,notes:''},
    {id:8,date:'2026-01-08',type:'Loan Given',details:'Shohorab Bhai',amountIn:0,amountOut:100000,notes:'Refundable',person:'Shohorab Bhai'},
    {id:9,date:'2026-01-09',type:'Spend',details:'Fuad',amountIn:0,amountOut:62000,notes:''},
    {id:10,date:'2026-01-10',type:'Spend',details:'Naina',amountIn:0,amountOut:15000,notes:''},
    {id:11,date:'2026-09-03',type:'Loan Received',details:'Riaz Loan Paid / Returned',amountIn:103200,amountOut:0,interestAmount:3200,notes:'৳1,00,000 principal + ৳3,200 interest',person:'Riaz'},
    {id:12,date:'2025-09-03',type:'Spend',details:'Land Registration Fee paid by Fuad',amountIn:0,amountOut:3000,notes:''},
    {id:13,date:'2026-09-03',type:'Adjustment',details:'Rounded balance adjustment',amountIn:0,amountOut:200,notes:'Added only to match recorded balance'},
    {id:14,date:'2026-05-20',type:'Spend',details:'Study Amount',amountIn:0,amountOut:150000,notes:''},
    {id:15,date:'2026-06-20',type:'Loan Given',details:'Loan to Mamun',amountIn:0,amountOut:100000,notes:'Refundable, 6 months',person:'Mamun'},
    {id:16,date:'2026-03-07',type:'Loan Received',details:'Shohorab Bhai loan returned',amountIn:100000,amountOut:0,notes:'Received and sent to Riaz as new loan',person:'Shohorab Bhai'},
    {id:17,date:'2026-03-07',type:'Loan Given',details:'Riaz Loan',amountIn:0,amountOut:100000,notes:'Refundable, 3 months; funded by Shohorab return',person:'Riaz'},
    {id:18,date:'2026-07-16',type:'Money Added',details:'Second land sale instalment',amountIn:875000,amountOut:0,notes:'৳8.75 lakh received'},
    {id:19,date:'2026-07-17',type:'Spend',details:'Send to Naina',amountIn:0,amountOut:10000,notes:'Naina Dutch Bangla Account'},
    {id:20,date:'2026-07-22',type:'Spend',details:'Linda Apu account for Bed and Almira',amountIn:0,amountOut:5000,notes:'Noakhali'},
    {id:21,date:'2026-07-22',type:'Spend',details:'Mamun Kozymart payment',amountIn:0,amountOut:1400,notes:''},
    {id:22,date:'2026-07-28',type:'Loan Given',details:'Loan to Mamun',amountIn:0,amountOut:100000,notes:'Refundable, 3 months',person:'Mamun'},
    {id:23,date:'2026-08-03',type:'Saving/FDR',details:'Naina BRAC FDR',amountIn:0,amountOut:500000,notes:'3 months, Acc: 1066151570001'},
    {id:24,date:'2026-08-08',type:'Loan Given',details:'Loan to Mamun',amountIn:0,amountOut:100000,notes:'Refundable, 3 months',person:'Mamun'},
    {id:25,date:'2026-07-22',type:'Spend',details:'Linda Apu account for Bed and Almira',amountIn:0,amountOut:19000,notes:'Noakhali'}
  ],
  loanAccounts:[
    {name:'Riaz',given:200000,receivedPrincipal:100000,interestEarned:3200,status:'Pending',note:'All Riaz loans combined'},
    {name:'Shohorab Bhai',given:100000,receivedPrincipal:100000,interestEarned:0,status:'Closed',note:'Returned in full'},
    {name:'Mamun',given:300000,receivedPrincipal:0,interestEarned:0,status:'Pending',note:'Refundable loans'}
  ]
};
let data=loadData();
function migrateData(saved){
  if(!saved)return structuredClone(seed);
  saved.originalLandSale=3375000;
  saved.transactions.forEach(x=>{if(x.person==='Riaz Loan 1'||x.person==='Riaz New Loan')x.person='Riaz';if(x.id===11&&!x.interestAmount)x.interestAmount=3200});
  const riazRepayment=saved.transactions.find(x=>x.id===11);if(riazRepayment)riazRepayment.notes='৳1,00,000 principal + ৳3,200 interest';
  const firstInstalment=saved.transactions.find(x=>x.id===1);if(firstInstalment){firstInstalment.details='First land sale instalment';firstInstalment.notes='৳25 lakh received'}
  const registrationFee=saved.transactions.find(x=>x.id===12);if(registrationFee)registrationFee.date='2025-09-03';
  const secondInstalment=saved.transactions.find(x=>x.id===18);if(secondInstalment){secondInstalment.details='Second land sale instalment';secondInstalment.notes='৳8.75 lakh received'}
  const accounts=saved.loanAccounts||[],riaz=accounts.filter(x=>['Riaz','Riaz Loan 1','Riaz New Loan'].includes(x.name));
  const others=accounts.filter(x=>!['Riaz','Riaz Loan 1','Riaz New Loan'].includes(x.name)).map(x=>({...x,receivedPrincipal:x.receivedPrincipal??x.received??0,interestEarned:x.interestEarned||0}));
  if(riaz.length)others.unshift({name:'Riaz',given:riaz.reduce((a,x)=>a+(+x.given||0),0),receivedPrincipal:riaz.reduce((a,x)=>a+(x.receivedPrincipal??Math.min(+x.received||0,+x.given||0)),0),interestEarned:riaz.reduce((a,x)=>a+(x.interestEarned||Math.max(0,(+x.received||0)-(+x.given||0))),0),status:'Pending',note:'All Riaz loans combined'});
  saved.loanAccounts=others;saved.loanAccounts.forEach(x=>x.status=(x.receivedPrincipal||0)>=x.given?'Closed':'Pending');return saved;
}
function loadData(){try{return migrateData(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return structuredClone(seed)}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function totals(){const t=data.transactions.reduce((a,x)=>({income:a.income+(+x.amountIn||0),out:a.out+(+x.amountOut||0)}),{income:0,out:0});const loans=data.loanAccounts.reduce((a,x)=>a+Math.max(0,x.given-(x.receivedPrincipal||0)),0);const savings=data.transactions.reduce((a,x)=>a+(x.type==='Saving/FDR'?x.amountOut:0)-(x.type==='Saving Withdrawn'?x.amountIn:0),0);const spend=data.transactions.filter(x=>x.type==='Spend'||x.type==='Adjustment').reduce((a,x)=>a+x.amountOut,0);return {...t,balance:t.income-t.out,loans,savings,spend,tracked:t.income-spend}}
function runningTransactions(){let bal=0;return [...data.transactions].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id).map(x=>({...x,balance:bal+=x.amountIn-x.amountOut}))}
function stat(icon,label,value,note='',tone=''){return `<article class="stat-card ${tone}"><div class="stat-icon">${icon}</div><p>${label}</p><h3>${money(value)}</h3>${note?`<small>${note}</small>`:''}</article>`}
function render(){const t=totals();document.querySelector('#dashboard-stats').innerHTML=stat('৳','Current money',t.balance,'Available in hand','cash-card')+stat('⇄','Pending loans',t.loans,'Principal expected','loan-card')+stat('🏦','Savings / FDR',t.savings,'Money kept in bank','saving-card')+stat('◇','Total land fund',data.originalLandSale,'৳25L + ৳8.75L','land-card');
  document.querySelector('#transaction-stats').innerHTML=stat('↓','Money in',t.income)+stat('↑','Money out',t.out)+stat('⌂','Current balance',t.balance)+stat('•','Entries',data.transactions.length).replace(money(data.transactions.length),String(data.transactions.length));
  renderRecent();renderAllocation(t);renderTransactions();renderExpenses();renderLoans();renderSavings();renderLand(t);populateTypes();populatePeople();
}
function renderRecent(){const rows=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,6);document.querySelector('#recent-list').innerHTML=rows.map(x=>`<div class="recent-item"><div class="activity-icon ${x.amountOut?'out':''}">${x.amountOut?'↑':'↓'}</div><div><b>${esc(x.details)}</b><small>${formatDate(x.date)} · ${esc(x.type)}</small></div><div class="amount ${x.amountIn?'in':'out'}">${x.amountIn?'+':'−'}${money(x.amountIn||x.amountOut)}</div></div>`).join('')}
function renderAllocation(t){const vals=[{label:'Savings / FDR',value:t.savings,color:'#1d6b4f'},{label:'Pending loans',value:t.loans,color:'#8eb5a5'},{label:'Current money',value:Math.max(t.balance,0),color:'#d5e3dc'}],total=vals.reduce((a,x)=>a+x.value,0)||1;let pos=0;const stops=vals.map(x=>{const start=pos;pos+=x.value/total*100;return `${x.color} ${start}% ${pos}%`}).join(',');document.querySelector('#donut').style.background=`conic-gradient(${stops})`;document.querySelector('#donut-total').textContent=money(total);document.querySelector('#allocation-legend').innerHTML=vals.map(x=>`<div class="legend-row"><i style="background:${x.color}"></i><span>${x.label}</span><b>${money(x.value)}</b></div>`).join('')}
function renderTransactions(){const q=document.querySelector('#search-transactions').value.toLowerCase(),type=document.querySelector('#filter-type').value;let rows=runningTransactions().reverse().filter(x=>(type==='all'||x.type===type)&&(`${x.details} ${x.notes}`.toLowerCase().includes(q)));document.querySelector('#transaction-table').innerHTML=rows.map(x=>`<tr><td>${formatDate(x.date)}</td><td><span class="type-pill ${x.amountIn?'in':''}">${esc(x.type)}</span></td><td class="details"><b>${esc(x.details)}</b>${x.notes?`<br><small class="muted">${esc(x.notes)}</small>`:''}</td><td class="amount in">${x.amountIn?money(x.amountIn):'—'}</td><td class="amount">${x.amountOut?money(x.amountOut):'—'}</td><td><b>${money(x.balance)}</b></td><td class="actions"><button onclick="removeEntry(${x.id})" title="Delete entry">×</button></td></tr>`).join('');document.querySelector('#transaction-empty').classList.toggle('hidden',rows.length>0)}
function renderExpenses(){const q=document.querySelector('#search-expenses').value.toLowerCase(),all=data.transactions.filter(x=>x.type==='Spend'),rows=[...all].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).filter(x=>(`${x.details} ${x.notes}`.toLowerCase().includes(q))),total=all.reduce((a,x)=>a+x.amountOut,0),largest=Math.max(0,...all.map(x=>x.amountOut));document.querySelector('#expense-stats').innerHTML=stat('▾','Total spent',total,'All recorded costs','expense-card')+stat('🧾','Expense entries',all.length,'Number of spending records','expense-card').replace(money(all.length),String(all.length))+stat('↑','Largest expense',largest,'Highest single cost','expense-card');document.querySelector('#expense-table').innerHTML=rows.map(x=>`<tr><td>${formatDate(x.date)}</td><td class="details"><b>${esc(x.details)}</b></td><td class="details muted">${esc(x.notes||'—')}</td><td class="amount expense-amount">−${money(x.amountOut)}</td></tr>`).join('');document.querySelector('#expense-empty').classList.toggle('hidden',rows.length>0)}
function renderLoans(){const given=data.loanAccounts.reduce((a,x)=>a+x.given,0),received=data.loanAccounts.reduce((a,x)=>a+(x.receivedPrincipal||0),0),interest=data.loanAccounts.reduce((a,x)=>a+(x.interestEarned||0),0),pending=Math.max(0,given-received);document.querySelector('#loan-stats').innerHTML=stat('↑','Principal given',given)+stat('↓','Principal returned',received)+stat('…','Still pending',pending)+stat('＋','Interest earned',interest);const cards=data.loanAccounts.map(loanCard).join('');document.querySelector('#loan-list').innerHTML=cards;document.querySelector('#loan-preview').innerHTML=data.loanAccounts.filter(x=>x.status!=='Closed').map(x=>`<article class="mini-loan"><header><b>${esc(x.name)}</b><span class="badge">Pending</span></header><h4>${money(Math.max(0,x.given-(x.receivedPrincipal||0)))}</h4><small>principal still due</small></article>`).join('')||'<p class="muted">All loans are closed.</p>'}
function loanCard(x){const received=x.receivedPrincipal||0,pending=Math.max(0,x.given-received),pct=Math.min(100,x.given?received/x.given*100:0),closed=pending<=0;return `<article class="record-card"><header><div class="record-avatar">${esc(x.name[0])}</div><div><b>${esc(x.name)}</b><small>${esc(x.note||'Loan account')}</small></div><span class="badge ${closed?'closed':''}">${closed?'Closed':'Pending'}</span></header><div class="record-values"><div><small>Given</small><b>${money(x.given)}</b></div><div><small>Principal back</small><b>${money(received)}</b></div><div><small>Interest</small><b>${money(x.interestEarned||0)}</b></div><div><small>Pending</small><b>${money(pending)}</b></div></div><div class="progress"><i style="width:${pct}%"></i></div></article>`}
function renderSavings(){const rows=data.transactions.filter(x=>x.type==='Saving/FDR'||x.type==='Saving Withdrawn').sort((a,b)=>b.date.localeCompare(a.date));const deposited=rows.filter(x=>x.type==='Saving/FDR').reduce((a,x)=>a+x.amountOut,0),withdrawn=rows.filter(x=>x.type==='Saving Withdrawn').reduce((a,x)=>a+x.amountIn,0);document.querySelector('#saving-stats').innerHTML=stat('▣','Current savings',deposited-withdrawn)+stat('↓','Total deposited',deposited)+stat('↑','Withdrawn',withdrawn)+stat('•','FDR entries',rows.length).replace(money(rows.length),String(rows.length));document.querySelector('#saving-list').innerHTML=rows.map(x=>`<article class="record-card"><header><div class="record-avatar">▣</div><div><b>${esc(x.details)}</b><small>${formatDate(x.date)}</small></div><span class="badge ${x.type==='Saving Withdrawn'?'':'closed'}">${x.type==='Saving Withdrawn'?'Withdrawn':'Deposited'}</span></header><h2>${money(x.amountOut||x.amountIn)}</h2><p class="record-note">${esc(x.notes||'No additional notes')}</p></article>`).join('')||'<p class="muted">No savings records yet.</p>'}
function renderLand(t){document.querySelector('#land-original').textContent=money(data.originalLandSale);document.querySelector('#land-stats').innerHTML=stat('1','First instalment',2500000,'৳25 lakh received','cash-card')+stat('2','Second instalment',875000,'৳8.75 lakh received','land-card')+stat('✓','Total received',3375000,'Complete land sale fund','saving-card')+stat('⌂','Current in hand',t.balance,'Available cash','cash-card');const rows=data.transactions.filter(x=>['Opening Balance','Money Added','Saving/FDR','Loan Given','Loan Received'].includes(x.type)).sort((a,b)=>b.date.localeCompare(a.date));document.querySelector('#land-timeline').innerHTML=rows.map(x=>`<div class="timeline-item"><header><b>${esc(x.details)}</b><b class="${x.amountIn?'amount in':''}">${x.amountIn?'+':'−'}${money(x.amountIn||x.amountOut)}</b></header><time>${formatDate(x.date)} · ${esc(x.type)}</time>${x.notes?`<p>${esc(x.notes)}</p>`:''}</div>`).join('')}
function populateTypes(){const sel=document.querySelector('#filter-type'),current=sel.value,types=[...new Set(data.transactions.map(x=>x.type))].sort();sel.innerHTML='<option value="all">All types</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');sel.value=types.includes(current)?current:'all'}
function populatePeople(){document.querySelector('#entry-person').innerHTML='<option value="">Select loan account</option>'+data.loanAccounts.map(x=>`<option>${esc(x.name)}</option>`).join('')+'<option value="__new">+ New person</option>'}
function formatDate(d){return new Date(d+'T00:00:00').toLocaleDateString('en-BD',{day:'numeric',month:'short',year:'numeric'})}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const ok=document.querySelector('#username').value===CREDENTIAL.user&&await sha256(document.querySelector('#password').value)===CREDENTIAL.hash;if(!ok){document.querySelector('#login-error').textContent='The user ID or password is incorrect.';return}sessionStorage.setItem('naina-auth','yes');showApp()});
document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('#password');p.type=p.type==='password'?'text':'password';document.querySelector('#toggle-password').textContent=p.type==='password'?'Show':'Hide'};
function showApp(){document.querySelector('#login-screen').classList.add('hidden');document.querySelector('#app').classList.remove('hidden');render();route()}
document.querySelector('#logout').onclick=()=>{sessionStorage.removeItem('naina-auth');location.reload()};
const titles={dashboard:'Overview',transactions:'Transactions',expenses:'Expenses / Spend',loans:'Loans',savings:'Savings & FDR',land:'Land fund',settings:'Backup & settings'};
function route(){const page=location.hash.slice(1)||'dashboard',valid=titles[page]?page:'dashboard';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===valid+'-page'));document.querySelectorAll('#nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===valid));document.querySelector('#page-title').textContent=titles[valid];document.querySelector('.sidebar').classList.remove('open');scrollTo(0,0)}window.addEventListener('hashchange',route);
document.querySelector('#menu-btn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelectorAll('[data-open-entry]').forEach(b=>b.onclick=()=>{document.querySelector('#entry-date').value=new Date().toISOString().slice(0,10);document.querySelector('#entry-modal').classList.remove('hidden')});document.querySelectorAll('.close-modal').forEach(b=>b.onclick=()=>document.querySelector('#entry-modal').classList.add('hidden'));
document.querySelector('#entry-type').onchange=e=>{const type=e.target.value;document.querySelector('#person-field').classList.toggle('hidden',!['Loan Given','Loan Received'].includes(type));document.querySelector('#interest-field').classList.toggle('hidden',type!=='Loan Received')};
document.querySelector('#entry-form').onsubmit=e=>{e.preventDefault();const type=document.querySelector('#entry-type').value,amount=+document.querySelector('#entry-amount').value,interest=type==='Loan Received'?+document.querySelector('#entry-interest').value||0:0,principal=amount-interest;let person=document.querySelector('#entry-person').value;if(interest>amount){toast('Interest cannot be more than the total received.');return}if(['Loan Given','Loan Received'].includes(type)&&person==='__new')person=prompt('Enter the person or loan account name:')?.trim();if(['Loan Given','Loan Received'].includes(type)&&!person){toast('Please select a loan account.');return}const incoming=['Money Added','Loan Received','Saving Withdrawn'].includes(type);data.transactions.push({id:Date.now(),date:document.querySelector('#entry-date').value,type,details:document.querySelector('#entry-details').value.trim(),amountIn:incoming?amount:0,amountOut:incoming?0:amount,interestAmount:interest,notes:document.querySelector('#entry-notes').value.trim(),person:person||''});if(type==='Loan Given'||type==='Loan Received'){let a=data.loanAccounts.find(x=>x.name===person);if(!a){a={name:person,given:0,receivedPrincipal:0,interestEarned:0,status:'Pending',note:'Added in the app'};data.loanAccounts.push(a)}if(type==='Loan Given')a.given+=amount;else{a.receivedPrincipal=(a.receivedPrincipal||0)+principal;a.interestEarned=(a.interestEarned||0)+interest}a.status=(a.receivedPrincipal||0)>=a.given?'Closed':'Pending'}saveData();render();e.target.reset();document.querySelector('#person-field').classList.add('hidden');document.querySelector('#interest-field').classList.add('hidden');document.querySelector('#entry-modal').classList.add('hidden');toast('Entry saved and totals updated.')};
window.removeEntry=id=>{if(!confirm('Delete this entry? This will update all totals.'))return;const x=data.transactions.find(y=>y.id===id);if(x?.person&&['Loan Given','Loan Received'].includes(x.type)){const a=data.loanAccounts.find(y=>y.name===x.person);if(a){if(x.type==='Loan Given')a.given-=x.amountOut;else{a.receivedPrincipal-=x.amountIn-(x.interestAmount||0);a.interestEarned-=x.interestAmount||0}a.status=(a.receivedPrincipal||0)>=a.given?'Closed':'Pending'}}data.transactions=data.transactions.filter(x=>x.id!==id);saveData();render();toast('Entry deleted.')};
document.querySelector('#search-transactions').oninput=renderTransactions;document.querySelector('#filter-type').onchange=renderTransactions;
document.querySelector('#search-expenses').oninput=renderExpenses;
document.querySelector('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`naina-money-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded.')};
document.querySelector('#import-data').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);if(!Array.isArray(parsed.transactions)||!Array.isArray(parsed.loanAccounts))throw Error();data=migrateData(parsed);saveData();render();toast('Backup restored successfully.')}catch{toast('That backup file is not valid.')}};reader.readAsText(file)};
document.querySelector('#reset-data').onclick=()=>{if(!confirm('Reset all changes and restore the original workbook data?'))return;data=structuredClone(seed);saveData();render();toast('Original workbook data restored.')};
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.add('hidden'),2800)}
document.querySelector('#today').textContent=new Date().toLocaleDateString('en-BD',{weekday:'long',day:'numeric',month:'long'});
if(sessionStorage.getItem('naina-auth')==='yes')showApp();
